version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://duck:123@db/mydb
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: duck
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  node_modules:
